/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Paneles;

/**
 *
 * @author Sergio Olmedo
 */
public class Dash extends javax.swing.JPanel {

    /**
     * Creates new form Dash
     */
    public Dash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDash = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CPU = new javax.swing.JPanel();
        lblIcono = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        Likes = new javax.swing.JPanel();
        lblIcono2 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblInfo2 = new javax.swing.JLabel();
        Sales = new javax.swing.JPanel();
        lblIcono1 = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        lblInfo1 = new javax.swing.JLabel();
        Likes1 = new javax.swing.JPanel();
        lblIcono3 = new javax.swing.JLabel();
        lblTitulo3 = new javax.swing.JLabel();
        lblInfo3 = new javax.swing.JLabel();

        pnlDash.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Dashboard");

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_dashboard_24px.png"))); // NOI18N
        jLabel7.setText("Home > Dash");
        jLabel7.setOpaque(true);

        CPU.setBackground(new java.awt.Color(255, 255, 255));

        lblIcono.setBackground(new java.awt.Color(51, 153, 255));
        lblIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_settings_48px.png"))); // NOI18N
        lblIcono.setOpaque(true);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(102, 102, 102));
        lblTitulo.setText("CPU Traffic");

        lblInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(51, 51, 51));
        lblInfo.setText("90%");

        javax.swing.GroupLayout CPULayout = new javax.swing.GroupLayout(CPU);
        CPU.setLayout(CPULayout);
        CPULayout.setHorizontalGroup(
            CPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CPULayout.createSequentialGroup()
                .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CPULayout.createSequentialGroup()
                        .addComponent(lblInfo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CPULayout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        CPULayout.setVerticalGroup(
            CPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CPULayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        Likes.setBackground(new java.awt.Color(255, 255, 255));

        lblIcono2.setBackground(new java.awt.Color(204, 0, 0));
        lblIcono2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_google_48px.png"))); // NOI18N
        lblIcono2.setOpaque(true);

        lblTitulo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(102, 102, 102));
        lblTitulo2.setText("Likes");

        lblInfo2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInfo2.setForeground(new java.awt.Color(51, 51, 51));
        lblInfo2.setText("4.140");

        javax.swing.GroupLayout LikesLayout = new javax.swing.GroupLayout(Likes);
        Likes.setLayout(LikesLayout);
        LikesLayout.setHorizontalGroup(
            LikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LikesLayout.createSequentialGroup()
                .addComponent(lblIcono2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LikesLayout.createSequentialGroup()
                        .addComponent(lblInfo2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(LikesLayout.createSequentialGroup()
                        .addComponent(lblTitulo2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        LikesLayout.setVerticalGroup(
            LikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcono2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LikesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo2)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        Sales.setBackground(new java.awt.Color(255, 255, 255));

        lblIcono1.setBackground(new java.awt.Color(0, 102, 0));
        lblIcono1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_sales_performance_48px.png"))); // NOI18N
        lblIcono1.setOpaque(true);

        lblTitulo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(102, 102, 102));
        lblTitulo1.setText("Sales");

        lblInfo1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInfo1.setForeground(new java.awt.Color(51, 51, 51));
        lblInfo1.setText("$525,33");

        javax.swing.GroupLayout SalesLayout = new javax.swing.GroupLayout(Sales);
        Sales.setLayout(SalesLayout);
        SalesLayout.setHorizontalGroup(
            SalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalesLayout.createSequentialGroup()
                .addComponent(lblIcono1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SalesLayout.createSequentialGroup()
                        .addComponent(lblInfo1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(SalesLayout.createSequentialGroup()
                        .addComponent(lblTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        SalesLayout.setVerticalGroup(
            SalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcono1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        Likes1.setBackground(new java.awt.Color(255, 255, 255));

        lblIcono3.setBackground(new java.awt.Color(255, 255, 102));
        lblIcono3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_user_groups_48px.png"))); // NOI18N
        lblIcono3.setOpaque(true);

        lblTitulo3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo3.setForeground(new java.awt.Color(102, 102, 102));
        lblTitulo3.setText("Members");

        lblInfo3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInfo3.setForeground(new java.awt.Color(51, 51, 51));
        lblInfo3.setText("4.140");

        javax.swing.GroupLayout Likes1Layout = new javax.swing.GroupLayout(Likes1);
        Likes1.setLayout(Likes1Layout);
        Likes1Layout.setHorizontalGroup(
            Likes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Likes1Layout.createSequentialGroup()
                .addComponent(lblIcono3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Likes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Likes1Layout.createSequentialGroup()
                        .addComponent(lblInfo3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Likes1Layout.createSequentialGroup()
                        .addComponent(lblTitulo3, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        Likes1Layout.setVerticalGroup(
            Likes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcono3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Likes1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo3)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDashLayout = new javax.swing.GroupLayout(pnlDash);
        pnlDash.setLayout(pnlDashLayout);
        pnlDashLayout.setHorizontalGroup(
            pnlDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashLayout.createSequentialGroup()
                .addGroup(pnlDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDashLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlDashLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlDashLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnlDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDashLayout.createSequentialGroup()
                                .addComponent(CPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Likes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDashLayout.createSequentialGroup()
                                .addComponent(Sales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Likes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 232, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDashLayout.setVerticalGroup(
            pnlDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(pnlDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Likes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Likes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(427, 427, 427))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CPU;
    private javax.swing.JPanel Likes;
    private javax.swing.JPanel Likes1;
    private javax.swing.JPanel Sales;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblIcono1;
    private javax.swing.JLabel lblIcono2;
    private javax.swing.JLabel lblIcono3;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblInfo1;
    private javax.swing.JLabel lblInfo2;
    private javax.swing.JLabel lblInfo3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JPanel pnlDash;
    // End of variables declaration//GEN-END:variables
}
